### PR TITLE
NXP-27049: add minimal ftest of the rendering and rendering-samples p…

### PR DESCRIPTION
**Pull request by atchertchian**
…ackages

see also https://github.com/nuxeo/integration-scripts/pull/52

### CODE REVIEW

**Comment by kevinleturc** [comment]
👍

**Comment by atchertchian** [comment]
https://qa.nuxeo.org/jenkins/job/master/job/addons_FT_nuxeo-template-rendering-NXP-27049/1/ shows the failure that we failed to identify: will rebase the branch to confirm it is fixed on master now

**Comment by atchertchian** [comment]
https://qa.nuxeo.org/jenkins/job/master/job/addons_FT_nuxeo-template-rendering-NXP-27049/2/ is showing that samples tests redirect to WEBUI so the standard login/logout test cannot be used as is

**Comment by guirenard** [comment]
:+1:

**Comment by atchertchian** [comment]
https://qa.nuxeo.org/jenkins/job/master/job/addons_FT_nuxeo-template-rendering-NXP-27049/3/ went through with latest changes

**Comment by guirenard** [comment]
:+1:

**Comment by kevinleturc** [comment]
:+1:

**Pull request merged**
