### PR TITLE
NXP-25182 fix template rendering & samples studio registries generation

### PR DESCRIPTION
**Pull request by bchauvin**

### CODE REVIEW

**Comment by bchauvin** [comment]
I need to backport this to 9.10 once PR is ok

**Review by Gabez0r — APPROVED** [review]

**Comment by Gabez0r** [comment]
👍

**Comment by jcarsique** [comment]
requesting review by @akervern

**Review by jcarsique — CHANGES_REQUESTED** [review]
can't review; please complete NXP-25182

**Review by akervern — APPROVED** [review]

**Pull request merged**
